syntax = "proto3";

package trace;

option go_package = "proto/gen/v1/trace";

message CallStack {
  Resource resource = 1;
  repeated Span spans = 2;
}

message Resource {
  map<string, string> attributes = 1;
}

message Span {
  string trace_id = 1;
  string span_id = 2;
  string parent_span_id = 3;

  string name = 4;

  string kind = 5;

  int64 start_time = 6;
  int64 end_time = 7;

  string status = 8;
  string error_message = 9;

  map<string, string> attributes = 10;

  repeated Event events = 11;
  repeated Link links = 12;
}

message Event {
  string name = 1;
  int64 timestamp = 2;
  map<string, string> attributes = 3;
}

message Link {
  string trace_id = 1;
  string span_id = 2;
  map<string, string> attributes = 3;
}
