name: LinDB Common CI
on: [push, pull_request]
jobs:
  test-with-coverage:
    name: Uint Test With Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
        id: go
      - name: Test
        run: make test
      - name: Upload
        run: bash <(curl -s https://codecov.io/bash) -t 0dc96dff-2c87-4f72-bd18-a4a816ebe107
