name: LinDB CI
on: [push, pull_request]
jobs:
  test-with-coverage:
    name: Uint Test With Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
        id: go
      - name: Test
        run: make test
